# Generated by Django 4.0.6 on 2022-08-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('servicio_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=25)),
                ('cliente', models.CharField(max_length=25)),
                ('precio', models.FloatField(max_length=10)),
                ('uso', models.IntegerField()),
            ],
        ),
    ]
